site_name: ratmod documentation
theme:
  name: readthedocs
  custom_dir: docs/theme
extra_css:
    - https://fonts.googleapis.com/css?family=Open+Sans:300,600
    - theme/theme.css
markdown_extensions:
  - admonition
site_description: ratmod documentation for openarena afps mod (docs)
use_directory_urls: false
nav:
  - Ratmod: index.md
  - Config and Command Reference: config-command-reference.md
  - Medal Reference: medal-reference.md
  - Callvote Reference: callvote-reference.md
  - Custom Game Types: game-types.md
  - Perfomance Tweaks: tweaks.md
  - FAQ: faq.md
  #- Change Log: changelog.md

