site_name: ratmod
theme:
  name: readthedocs
  custom_dir: docs/theme
extra_css:
    - https://fonts.googleapis.com/css?family=Open+Sans:300,600
    - theme/theme.css
markdown_extensions:
  - admonition
site_description: by the rats, for the rats
use_directory_urls: false
nav:
  - Ratmod: index.md
  - Getting Started with Ratmod: getting-started.md
  - Medal Reference: medal-reference.md
  - Features: features.md
  - FAQ: faq.md
